-- Generated by tools/generate-name-reuse.py from ItemSparse.json Display_lang.
-- Each enUS value has exactly one other itIT translation in the same field.
local _, ns = ...
ns.data = ns.data or {}
ns.data.items = ns.data.items or {}
local reused = {
    [2444] = { en = "Ornate Buckler", name = "Brocchiero Decorato" },
    [6136] = { en = "Thug Shirt", name = "Camicia da Teppista" },
    [6138] = { en = "Thug Boots", name = "Stivali da Teppista" },
    [7716] = { en = "Shattered Necklace", name = "Collana Infranta" },
    [9092] = { en = "Tablet of Sentry Totem", name = "Tavoletta del Totem Avvistatore" },
    [10595] = { en = "Kum'isha's Junk", name = "Cianfrusaglie di Kum'isha" },
    [11079] = { en = "Gor'tesh's Lopped Off Head", name = "Testa Mozzata di Gor'tesh" },
    [11099] = { en = "Dark Iron Ore", name = "Minerale di Ferroscuro" },
    [11442] = { en = "Stormwind Deputy Kit", name = "Attrezzi del Vicesceriffo di Roccavento" },
    [20090] = { en = "Highlander's Chain Girdle", name = "Cinturone Inanellato degli Altopiani" },
    [20093] = { en = "Highlander's Chain Greaves", name = "Schinieri Inanellati degli Altopiani" },
    [20126] = { en = "Highlander's Plate Girdle", name = "Cinturone di Piastre degli Altopiani" },
    [20129] = { en = "Highlander's Plate Greaves", name = "Schinieri di Piastre degli Altopiani" },
    [20197] = { en = "Defiler's Mail Girdle", name = "Cinturone di Maglia dei Profanatori" },
    [20207] = { en = "Defiler's Plate Girdle", name = "Cinturone di Piastre dei Profanatori" },
    [20210] = { en = "Defiler's Plate Greaves", name = "Schinieri di Piastre dei Profanatori" },
    [20475] = { en = "Soul Gem", name = "Gemma dell'Anima" },
    [23314] = { en = "Lieutenant Commander's Plate Helm", name = "Elmo di Piastre del Tenente Comandante" },
    [210980] = { en = "Rune of Metamorphosis", name = "Runa della Metamorfosi" },
    [236878] = { en = "Mysterious Relic", name = "Reliquia Misteriosa" },
    [236879] = { en = "Mysterious Relic", name = "Reliquia Misteriosa" },
    [236880] = { en = "Mysterious Relic", name = "Reliquia Misteriosa" },
    [243065] = { en = "Broken Wand", name = "Bacchetta Rotta" },
    [243177] = { en = "Ingenious Toy", name = "Giocattolo Ingegnoso" },
    [248206] = { en = "Sealed Craftsman's Writ", name = "Contratto d'Artigianato Sigillato" },
    [252425] = { en = "Dark Leather Boots", name = "Stivali di Cuoio Scuro" },
    [254841] = { en = "Petrified Bark", name = "Corteccia Pietrificata" },
    [268815] = { en = "Bone Fragments", name = "Frammento d'Osso" },
    [269718] = { en = "Bundle of Hides", name = "Mucchio di Pelli" },
    [270094] = { en = "Black Whelp Boots", name = "Stivali di Draghetto Nero" },
    [272432] = { en = "Totem of the Storm", name = "Totem della Tempesta" },
    [274974] = { en = "Message in a Bottle", name = "Messaggio nella Bottiglia" },
    [280911] = { en = "Spiked Collar", name = "Collare Chiodato" },
    [282419] = { en = "Crumpled Note", name = "Nota Sgualcita" },
    [282422] = { en = "Simple Note", name = "Nota Semplice" },
}
for id, record in pairs(reused) do
    local current = ns.data.items[id]
    if current == nil then
        ns.data.items[id] = record
    elseif type(current) == "table" and current.name == nil and
           (current.en == nil or current.en == record.en) then
        current.en = current.en or record.en
        current.name = record.name
    end
end
