"""Apply a verified item description to identical local ItemSparse DB2 text."""

from __future__ import annotations

import json
import os
from collections import defaultdict
from pathlib import Path

from lupa import LuaRuntime

from generate_spell_reuse import lua_string


ROOT = Path(__file__).resolve().parents[1]
ADDON = ROOT / "Addon"
SOURCE = Path(os.environ.get("TEMP", ".")) / "wfi-casc-audit" / "locale-verified" / "ItemSparse.json"
OUTPUT = ADDON / "Data" / "ItemTranslationAliases.lua"


def main() -> None:
    items = {entry["id"]: entry for entry in
             json.loads(SOURCE.read_text(encoding="utf-8"))["entries"]}
    lua = LuaRuntime(unpack_returned_tuples=True)
    lua.execute("WFI_DB = {}; SlashCmdList = {}; CreateFrame = function() return { RegisterEvent=function() end, SetScript=function() end } end")
    namespace = lua.table()
    for row in (ADDON / "WOWForverItaliano.toc").read_text(encoding="utf-8-sig").splitlines():
        name = row.strip()
        if name == "Data\\ItemTranslationAliases.lua":
            continue
        if name == "Core.lua" or (name.startswith("Data\\") and name.endswith(".lua")):
            lua.execute((ADDON / name.replace("\\", "/")).read_text(encoding="utf-8"),
                        "WOWForverItaliano", namespace)
    data = namespace.data
    overrides = data.itemDescriptionOverrides

    known: dict[str, set[str]] = defaultdict(set)
    for item_id, record in overrides.items():
        source = items.get(int(item_id)) or {}
        field = source.get("Description_lang") or {}
        if record.enDescription == field.get("enUS") and record.description != record.enDescription:
            known[record.enDescription].add(record.description)
    for item_id, record in data["items"].items():
        source = items.get(int(item_id)) or {}
        field = source.get("Description_lang") or {}
        if (record.enDescription and record.description and
                record.enDescription == field.get("enUS") and
                record.description != record.enDescription):
            known[record.enDescription].add(record.description)

    selected = []
    for item_id, item in items.items():
        name = item.get("Display_lang") or {}
        field = item.get("Description_lang") or {}
        english, current = field.get("enUS"), field.get("itIT")
        options = known.get(english or "", ())
        if (not english or "$" in english or
                (current and current != english) or
                overrides[item_id] is not None or
                (data["items"][item_id] is not None and
                 data["items"][item_id].description is not None) or
                len(options) != 1 or
                not name.get("enUS")):
            continue
        italian = next(iter(options))
        if "$" in italian or italian == english:
            continue
        selected.append((item_id, name["enUS"], name.get("itIT"), english, italian))

    lines = [
        "-- Generated by tools/generate-item-aliases.py from exact ItemSparse.db2 text matches.",
        "-- Each source description has one previously verified Italian translation.",
        "local _, ns = ...",
        "ns.data = ns.data or {}",
        "ns.data.itemDescriptionOverrides = ns.data.itemDescriptionOverrides or {}",
        "local aliases = {",
    ]
    for item_id, en_name, it_name, english, italian in sorted(selected):
        name_part = f", itName = {lua_string(it_name)}" if it_name else ""
        lines.append(f"    [{item_id}] = {{ enName = {lua_string(en_name)}{name_part}, "
                     f"enDescription = {lua_string(english)}, "
                     f"description = {lua_string(italian)} }},")
    lines += [
        "}",
        "for id, record in pairs(aliases) do",
        "    if ns.data.itemDescriptionOverrides[id] == nil then",
        "        ns.data.itemDescriptionOverrides[id] = record",
        "    end",
        "end",
    ]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"item_aliases={len(selected)} unique_english={len(set(en for _, _, _, en, _ in selected))} "
          f"output={OUTPUT}")


if __name__ == "__main__":
    main()
