"""Record exact local spell names to gate insertion of missing static bodies."""

import json
import os
from pathlib import Path

from lupa import LuaRuntime

from generate_spell_reuse import TRUSTED_DONOR_MAX_ID, lua_string


ROOT = Path(__file__).resolve().parents[1]
ADDON = ROOT / "Addon"
SOURCE = Path(os.environ.get("TEMP", ".")) / "wfi-casc-audit" / "locale-verified" / "SpellName.json"
OUTPUT = ADDON / "Data" / "SpellStaticSourceNames.lua"


def main():
    lua = LuaRuntime(unpack_returned_tuples=True)
    lua.execute("WFI_DB = {}; SlashCmdList = {}; CreateFrame = function() return { RegisterEvent=function() end, SetScript=function() end } end")
    namespace = lua.table()
    for row in (ADDON / "WOWForverItaliano.toc").read_text(encoding="utf-8-sig").splitlines():
        name = row.strip()
        if name == "Data\\SpellStaticSourceNames.lua":
            continue
        if name == "Core.lua" or (name.startswith("Data\\") and name.endswith(".lua")):
            lua.execute((ADDON / name.replace("\\", "/")).read_text(encoding="utf-8"),
                        "WOWForverItaliano", namespace)
    data = namespace.data
    static_ids = {int(spell_id) for spell_id, record in
                  data.spellDescriptionOverrides.items()
                  if record.description and "$" not in record.description}
    static_ids.update(int(spell_id) for spell_id, record in data.spells.items()
                      if record.description and "$" not in record.description)
    names = {entry["id"]: entry["Name_lang"] for entry in
             json.loads(SOURCE.read_text(encoding="utf-8"))["entries"]}
    lines = [
        "-- Generated by tools/generate-spell-source-names.py from local SpellName.db2.",
        "-- Used only to verify a tooltip before adding a missing token-free body.",
        "local _, ns = ...",
        "ns.data = ns.data or {}",
        "ns.data.spellSourceNames = {",
    ]
    included = 0
    for spell_id in sorted(static_ids):
        field = names.get(spell_id) or {}
        english, italian = field.get("enUS"), field.get("itIT")
        if not english or len(english) > 200:
            continue
        italian_part = (f", it = {lua_string(italian)}"
                        if spell_id < TRUSTED_DONOR_MAX_ID and
                        italian and italian != english else "")
        lines.append(f"    [{spell_id}] = {{ en = {lua_string(english)}{italian_part} }},")
        included += 1
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"static_names={included} output={OUTPUT}")


if __name__ == "__main__":
    main()
