"""Reuse an unambiguous Italian name from the same local DB2 name field.

Only an exact English match with one existing Italian value is accepted. The
addon still checks the source ID and the live tooltip title before display.
"""

from __future__ import annotations

import argparse
import json
import os
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = Path(os.environ.get("TEMP", ".")) / "wfi-casc-audit" / "locale-verified"
KINDS = {
    "spell": ("SpellName.json", "Name_lang", "spells", "name"),
    "item": ("ItemSparse.json", "Display_lang", "items", "name"),
}
# The beta's higher-ID itIT records include unrelated reused Italian strings
# (for example, an Earth Shield record says "Crudeltà"). Use established
# low-ID client records as donors, while allowing any ID as an exact target.
TRUSTED_DONOR_MAX_ID = 100_000


def safe(value: str) -> bool:
    return bool(value and len(value) <= 180 and "\n" not in value and
                "\r" not in value and "\ufffd" not in value and "$" not in value)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("kind", choices=KINDS)
    arguments = parser.parse_args()
    file_name, field_name, registry, translated_key = KINDS[arguments.kind]
    entries = json.loads((SOURCE_DIR / file_name).read_text(encoding="utf-8"))["entries"]

    known: dict[str, set[str]] = defaultdict(set)
    for entry in entries:
        if entry["id"] >= TRUSTED_DONOR_MAX_ID:
            continue
        field = entry.get(field_name) or {}
        english, italian = field.get("enUS"), field.get("itIT")
        if safe(english) and safe(italian) and english != italian:
            known[english].add(italian)

    selected: list[tuple[int, str, str]] = []
    for entry in entries:
        field = entry.get(field_name) or {}
        english, current = field.get("enUS"), field.get("itIT")
        if not safe(english) or (current and current != english):
            continue
        options = known.get(english, ())
        if len(options) != 1:
            continue
        selected.append((entry["id"], english, next(iter(options))))

    output = ROOT / "Addon" / "Data" / ("Spell" if arguments.kind == "spell" else "Item")
    output = output.with_name(output.name + "NameTranslationMemory.lua")
    lines = [
        f"-- Generated by tools/generate-name-reuse.py from {file_name} {field_name}.",
        "-- Each enUS value has exactly one other itIT translation in the same field.",
        "local _, ns = ...",
        "ns.data = ns.data or {}",
        f"ns.data.{registry} = ns.data.{registry} or {{}}",
        "local reused = {",
    ]
    for identifier, english, italian in selected:
        lines.append(f"    [{identifier}] = {{ en = {json.dumps(english, ensure_ascii=False)}, "
                     f"{translated_key} = {json.dumps(italian, ensure_ascii=False)} }},")
    lines += [
        "}",
        "for id, record in pairs(reused) do",
        f"    local current = ns.data.{registry}[id]",
        "    if current == nil then",
        f"        ns.data.{registry}[id] = record",
        "    elseif type(current) == \"table\" and current.name == nil and",
        "           (current.en == nil or current.en == record.en) then",
        "        current.en = current.en or record.en",
        "        current.name = record.name",
        "    end",
        "end",
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{arguments.kind}_name_reused={len(selected)} output={output}")


if __name__ == "__main__":
    main()
