"""Propagate verified Italian spell translations to identical English DB2 text."""

from __future__ import annotations

import argparse
import json
import os
from collections import defaultdict
from pathlib import Path

from lupa import LuaRuntime

from generate_spell_reuse import tokens_compatible, lua_string


ROOT = Path(__file__).resolve().parents[1]
ADDON = ROOT / "Addon"
SOURCE = Path(os.environ.get("TEMP", ".")) / "wfi-casc-audit" / "locale-verified" / "Spell.json"
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--aura", action="store_true",
                        help="use AuraDescription_lang instead of Description_lang")
    arguments = parser.parse_args()
    field_name = "AuraDescription_lang" if arguments.aura else "Description_lang"
    registry = ("spellAuraDescriptionOverrides" if arguments.aura else
                "spellDescriptionOverrides")
    output_name = ("SpellAuraTranslationAliases.lua" if arguments.aura else
                   "SpellTranslationAliases.lua")
    output = ADDON / "Data" / output_name
    source = {
        entry["id"]: entry[field_name]
        for entry in json.loads(SOURCE.read_text(encoding="utf-8"))["entries"]
        if field_name in entry
    }
    lua = LuaRuntime(unpack_returned_tuples=True)
    lua.execute("WFI_DB = {}; SlashCmdList = {}; CreateFrame = function() return { RegisterEvent=function() end, SetScript=function() end } end")
    namespace = lua.table()
    for row in (ADDON / "WOWForverItaliano.toc").read_text(encoding="utf-8-sig").splitlines():
        name = row.strip()
        if (name == "Data\\" + output_name or
                not (name == "Core.lua" or name.startswith("Data\\")) or
                not name.lower().endswith(".lua")):
            continue
        lua.execute((ADDON / name.replace("\\", "/")).read_text(encoding="utf-8"),
                    "WOWForverItaliano", namespace)

    existing = namespace.data[registry]
    known: dict[str, set[str]] = defaultdict(set)
    for spell_id, record in existing.items():
        field = source.get(int(spell_id))
        if field and record.en == field.get("enUS") and record.description != record.en:
            known[record.en].add(record.description)

    aliases = []
    for spell_id, field in source.items():
        english, italian = field.get("enUS"), field.get("itIT")
        if (not english or (italian and italian != english) or
                existing[spell_id] is not None or len(known.get(english, ())) != 1):
            continue
        target = next(iter(known[english]))
        if (not tokens_compatible(english, target) or
                len(english) > 1600 or len(target) > 1600):
            continue
        aliases.append((spell_id, english, target))

    lines = [
        f"-- Generated by tools/generate-spell-aliases.py from exact Spell.db2 {field_name} matches.",
        "-- Each source English text has one previously verified Italian translation.",
        "local _, ns = ...",
        "ns.data = ns.data or {}",
        f"ns.data.{registry} = ns.data.{registry} or {{}}",
        "local aliases = {",
    ]
    for spell_id, english, italian in sorted(aliases):
        lines.append(f"    [{spell_id}] = {{ en = {lua_string(english)}, description = {lua_string(italian)} }},")
    lines += [
        "}",
        "for id, record in pairs(aliases) do",
        f"    if ns.data.{registry}[id] == nil then",
        f"        ns.data.{registry}[id] = record",
        "    end",
        "end",
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"aliases={len(aliases)} unique_english={len(set(en for _, en, _ in aliases))} "
          f"output={output}")


if __name__ == "__main__":
    main()
